# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "30 1 * * *" # run at 1:30 AM UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # matrix dosc: https://github.com/actions/runner-images/blob/ubuntu22/20221027.1/images/linux/Ubuntu2204-Readme.md
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python version docs: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python-version:
          - 3.10.8

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install packages
        run: sudo apt-get install -y moreutils librsvg2-bin

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # python setup docs: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          make install
          make patch python_lib_path=/home/runner/.local/lib/python3.10/site-packages
          make vendor
          make build

      - uses: actions/upload-artifact@v2
        with:
          name: cncf-stencil
          path: ./output/*.gstencil.zip
